############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
#  port: 8003
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-all

  datasource:
    url: jdbc:mysql://47.99.136.24:3306/ziyunying?useSSL=false&serverTimezone=UTC
    username: root1
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#      druid:
#        aop-patterns: com.atguigu.admin.*  #监控SpringBean
#        filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
#        stat-view-servlet: # 配置监控页功能
#          enabled: true
#          login-username: admin
#          login-password: admin
#          resetEnable: false
#        web-stat-filter: # 监控web
#          enabled: true
#          urlPattern: /*
#          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#        filter:
#          stat: # 对上面filters里面的stat的详细配置
#            slow-sql-millis: 1000
#            logSlowSql: true
#            enabled: true
#          wall:
#            enabled: true
#            config:
#              drop-table-allow: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.fzz.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
## 通用 AppUserMapper 配置
#mapper:
#  mappers: com.imooc.my.mapper.MyMapper
#  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
#  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
